# streamlit secrets

# login password
login_password = "financerock!"

# DB credentials
[postgres]
host = 'ls-b5e85ef554c9924819da56c7278214bc2ce922cb.cpnoqscz27nt.us-east-1.rds.amazonaws.com'
port = 5432

user = "dbmasteruser"
dbname = "postgres"
password = "r1!U!Rj<G9fQF$^-Qfr1jq=r`EYWsP(."
